In [ ]:
# Install
!pip install numpy

In [1]:
import numpy as np

### Basics

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
# dimensions
a.ndim

2

In [6]:
a.shape

(2, 4)

In [7]:
# reshape
a.reshape((4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [8]:
a.reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
a.itemsize

8

### Accessing element in array

In [10]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
# Get a specific element [r,c]
a[1,2]

7

In [12]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4])

In [13]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:3:2]

array([2])

In [14]:
# Assign value 
a[0,2] = 10
a

array([[ 1,  2, 10,  4],
       [ 5,  6,  7,  8]])

In [15]:
# 3-d examples
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
# Get the specific value (works outside in)
b[1,0,0]

5

## Initializing Different Types of Arrays

In [17]:
# All zero's Matrix
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
# All one's Matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
# Any other number
np.full((3,3),9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [20]:
a

array([[ 1,  2, 10,  4],
       [ 5,  6,  7,  8]])

In [21]:
# Any other number (full_like)
np.full_like(a, 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5]])

In [25]:
# Random decimal numbers
np.random.rand(2,3)

array([[0.95448374, 0.31687361, 0.56462916],
       [0.86236326, 0.63474234, 0.69794786]])

In [28]:
# Random Interger values
np.random.randint(-4,8, size=(3,3))

array([[ 1,  1, -1],
       [ 7,  4,  1],
       [ 5,  6, -4]])

In [31]:
# Indentity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
# Repeat an array
arr = np.array([[2,4,6]])
r1 = np.repeat(arr,3)
r1

array([2, 2, 2, 4, 4, 4, 6, 6, 6])

In [46]:
r2 = np.repeat(arr,3,axis=0)
r2

array([[2, 4, 6],
       [2, 4, 6],
       [2, 4, 6]])

In [48]:
# For copying arrays
b = a.copy()
b

array([[ 1,  2, 10,  4],
       [ 5,  6,  7,  8]])

In [51]:
b[0][1] = 9

In [52]:
a

array([[ 1,  2, 10,  4],
       [ 5,  6,  7,  8]])

In [53]:
b

array([[ 1,  9, 10,  4],
       [ 5,  6,  7,  8]])

## Mathematics

In [54]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [55]:
a + 2

array([3, 4, 5, 6])

In [56]:
a - 2

array([-1,  0,  1,  2])

In [57]:
a * 2

array([2, 4, 6, 8])

In [58]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [59]:
b  = np.array([1,0,0,1])
a + b

array([2, 2, 3, 5])

In [60]:
a ** 2

array([ 1,  4,  9, 16])

In [61]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Statistics

In [71]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [72]:
np.min(stats)

1

In [74]:
np.max(stats)

6

In [75]:
np.max(stats,axis=1)

array([3, 6])

In [76]:
np.sum(stats)

21

In [77]:
np.sum(stats,axis=0)

array([5, 7, 9])

## Reshaping the array

In [79]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
stats.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [81]:
stats.reshape((1,6))

array([[1, 2, 3, 4, 5, 6]])

In [83]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [84]:
# Horizontal stack

np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])