In [1]:
import numpy as np

### Basics

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
a = np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
# dimensions
a.ndim

2

In [6]:
a.shape

(2, 4)

In [7]:
# reshape
a.reshape((4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [8]:
a.reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
a.itemsize

8

### Accessing element in array

In [10]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
# Get a specific element [r,c]
a[1,2]

7

In [12]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4])

In [13]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:3:2]

array([2])

In [16]:
# Assign value 
a[0,2] = 10
a

array([[ 1,  2, 10,  4],
       [ 5,  6,  7,  8]])

In [17]:
# 3-d examples
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [22]:
# Get the specific value (works outside in)
b[1,0,0]

5

## Initializing Different Types of Arrays

In [23]:
# All zero's Matrix
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
# All one's Matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
# Any other number
np.full((3,3),9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])